#!/usr/bin/env python3
"""Map layers of Kristiansund for the exploded plate -> docs/proposal/layers.json

Reads the OpenStreetMap extract (route relations arrive as ways tagged route=bus) and keeps, in UTM 32N metres: building footprints by use (homes,
apartments, work), the drivable network split into rv. 70 and the rest, bus routes, and the coast.
Footprints are simplified; every class count is printed so the plate states measured numbers.

    python docs/proposal/make_layers.py
"""
import bz2
import json
import xml.etree.ElementTree as ET
from collections import Counter
from pathlib import Path

from pyproj import Transformer
from shapely.geometry import LineString, Polygon

ROOT = Path(__file__).resolve().parents[2]
HOMES = {"house", "detached", "semidetached_house", "terrace", "residential", "farm", "cabin", "bungalow"}
FLATS = {"apartments", "dormitory"}
WORK = {"retail", "commercial", "industrial", "office", "warehouse", "supermarket", "hotel", "school",
        "kindergarten", "hospital", "public", "church", "university", "civic", "government", "college"}
DRIVE = {"motorway", "trunk", "primary", "secondary", "tertiary", "unclassified", "residential",
         "living_street", "motorway_link", "trunk_link", "primary_link", "secondary_link"}


def main():
    tr = Transformer.from_crs(4326, 32632, always_xy=True)
    nodes, ways, bus_ways = {}, {}, set()
    for _, el in ET.iterparse(bz2.open(ROOT / "data/osm/kristiansund.osm.bz2")):
        if el.tag == "node":
            nodes[el.get("id")] = tr.transform(float(el.get("lon")), float(el.get("lat")))
        elif el.tag == "way":
            ways[el.get("id")] = ([nd.get("ref") for nd in el.findall("nd")], {t.get("k"): t.get("v") for t in el.findall("tag")})
        elif el.tag == "relation":
            tags = {t.get("k"): t.get("v") for t in el.findall("tag")}
            if tags.get("route") == "bus":
                bus_ways.update(m.get("ref") for m in el.findall("member") if m.get("type") == "way")
        if el.tag in ("node", "way", "relation"):
            el.clear()

    def coords(refs):
        return [nodes[r] for r in refs if r in nodes]

    bld, cls_count, roads, rv70, bus = [], Counter(), [], [], []
    for wid, (refs, tags) in ways.items():
        b = tags.get("building")
        if b and b not in ("garage", "garages", "shed", "carport", "roof", "boathouse"):
            c = coords(refs)
            if len(c) >= 4:
                cls = "flat" if b in FLATS else "work" if b in WORK else "home"
                poly = Polygon(c).simplify(1.5)
                if poly.is_valid and poly.area > 15:
                    bld.append([cls, [[round(x), round(y)] for x, y in poly.exterior.coords][:-1]])
                    cls_count[cls] += 1
        h = tags.get("highway")
        if h in DRIVE:
            line = LineString(coords(refs)).simplify(2.0)
            pts = [[round(x), round(y)] for x, y in line.coords]
            (rv70 if tags.get("ref") == "70" else roads).append(pts)
        if (wid in bus_ways or tags.get("route") == "bus") and len(refs) > 1:
            line = LineString(coords(refs)).simplify(2.0)
            bus.append([[round(x), round(y)] for x, y in line.coords])
    towns = json.loads((ROOT / "docs/proposal/towns.json").read_text())["kristiansund"]
    out = {"note": "generated by docs/proposal/make_layers.py from OpenStreetMap (ODbL)",
           "bbox": towns["bbox"], "sea": towns["sea"], "buildings": bld, "classes": dict(cls_count),
           "roads": roads, "rv70": rv70, "bus": bus}
    (ROOT / "docs/proposal/layers.json").write_text(json.dumps(out, separators=(",", ":")))
    print("buildings", dict(cls_count), "roads", len(roads), "rv70", len(rv70), "bus ways", len(bus),
          "size kB", round(len(json.dumps(out)) / 1024))


if __name__ == "__main__":
    main()
