#!/usr/bin/env python3
"""Is the Kristiansund toll bridge captive? -> docs/proposal/bridge.json

Remove Nordsundbrua (rv. 70, the site of one of the two toll stations of Bypakke Kristiansund) from the
OpenStreetMap road graph and measure what is left: the connected parts, the share of junction pairs that
lose every road connection, and the share of buildings (the random sample in towns.json) on each side.
The second station, at Omsundbrua, lies outside the extract.

    python docs/proposal/make_bridge.py      # ~1 min
"""
import bz2
import json
import os
import sys
import tempfile
from pathlib import Path

import networkx as nx
import numpy as np
from scipy.spatial import cKDTree

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "skills" / "osm-network" / "scripts"))
import osm_network as on  # noqa: E402

BRIDGE = "Nordsundbrua"


def names(d):
    n = d.get("name")
    return n if isinstance(n, list) else [n]


def main():
    with tempfile.NamedTemporaryFile(suffix=".osm", delete=False) as tmp:
        tmp.write(bz2.open(ROOT / "data/osm/kristiansund.osm.bz2").read())
    try:
        G = on.load(osm=tmp.name)
    finally:
        os.unlink(tmp.name)
    bridge = [(u, v) for u, v, d in G.edges(data=True) if BRIDGE in names(d)]
    assert bridge, "bridge not found in the extract"
    U = G.to_undirected()
    U = U.subgraph(max(nx.connected_components(U), key=len)).copy()
    n = U.number_of_nodes()
    U.remove_edges_from(bridge)
    parts = sorted(nx.connected_components(U), key=len, reverse=True)
    cut = 1 - sum(len(c) * (len(c) - 1) for c in parts) / (n * (n - 1))

    side = {node: i for i, c in enumerate(parts[:2]) for node in c}
    ids = [node for node in G.nodes if node in side]
    xy = np.array([[G.nodes[i]["x"], G.nodes[i]["y"]] for i in ids])
    pts = np.array(json.loads((ROOT / "docs/proposal/towns.json").read_text())["kristiansund"]["points"])
    _, nearest = cKDTree(xy).query(pts)
    bside = np.array([side[ids[j]] for j in nearest])
    out = {
        "note": "generated by docs/proposal/make_bridge.py from OpenStreetMap (ODbL)",
        "bridge": BRIDGE, "junctions": n, "parts": [len(c) for c in parts[:3]],
        "pairs_cut": round(float(cut), 3),
        "buildings_sampled": int(len(pts)), "buildings_far_side": round(float((bside == 1).mean()), 3),
        "bridge_xy": [[round(G.nodes[u]["x"]), round(G.nodes[u]["y"])] for u, _ in bridge],
        "side": bside.tolist(),
    }
    (ROOT / "docs/proposal/bridge.json").write_text(json.dumps(out, separators=(",", ":")))
    print({k: v for k, v in out.items() if k != "side"})


if __name__ == "__main__":
    main()
